apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
    - name: hello-world
      image: alpine
      command: ["/bin/sh", "echo", "'Hello'"]
#      args:
#        - echo "Hello, World!"
