# https://hub.helm.sh/charts/stable/prometheus-operator
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: vosa-develop
spec:
  forceUpgrade: false
  resetValues: true
  timeout: 300
  wait: true
  maxHistory: 10
  rollback:
    enable: true
    retry: true
    maxRetries: 2
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 8.13.7
  values:
    # Only one operator can run in the cluster.
    prometheusOperator:
      enabled: false
    prometheus:
      prometheusSpec:
        retentionSize: 1Gi
        retention: 1d
    coreDns:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeStateMetrics:
      enabled: false
    kubelet:
      enabled: false
    nodeExporter:
      enabled: false
