apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secrets
  namespace: vosa-develop
spec:
  encryptedData:
    mySecretName: AgCRtmfE15OGZvi2uHs6BZZk8z9M1x693qSpL3PdUpdtAhJ9gDesiwThGd5QfsNigq9n0xH9mtjdcmpYwWsNZ79txrgyPz+Ws0x3q0519SSkTTwYo8HLy/WK44sey2cXURq0wjmqu/4+gWjqjYljlAmeicF060PTHH+0s3jcUiDxsKHAY5KR8GvAJMZ8LEVR3ljYIosipf9j0Uj0sNjSVZW4ZwCxMA19cTeDYyHJS5IdsGqsjMgrNDorT3XfMCFh/nBzRAYUgxRiMn+smS++vX5nVzNH+koKTkXheMFXoxZ6Lhxz3XePunCrdgyOgWfoFVBNcs538JlvrnUpoZHPfAEL/MWq3bmaVlN1faK5v0rg5UP3gqdOVmg7NW1Y7601oYS/Fcvyouyqq8hJh7Jo/NbhMMPtA1o2tn+DHuNG/A4lTxatqdj4gVBF+S0ngaBTXQUMgx/63xXUM9tqvXW46PzoLQnOjbOqt2nK/p5a+8ePjMASqji7v+79mdXCIDSTgrTDBRVdxCPSggHDsv1xCQToLvnWABqrGVMW0Omthv0b1q0jm83VjtAEVYHAYk5PgVrBnCnFuLKILLC6vDhOHXWk67w9DClXxPuRI4UjpXJJnZtGhyRlaGisjRVDk0A8P5FjMQE6fnzXO5X26xnGxS1dQ7V71ixVF0tWmewWmXPO/V8YqKypS0P5vp8+lQbSur5A7oPiyzj7AI4+pKaMsqk=
