apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret-name
  namespace: vosa-develop
spec:
  encryptedData:
    my-secret-key: "AgCxu/RcQjFazitGWBE3H5TsgFHl6f2V878KZCxgS9vsS1GXiCf4MMkO2YOTUF3rWhTTImGXxs+NUPPcW9CM5EYI4PFPEwjxSETbztd15z6q+xba7JiFWJpcflwf1qjOqyxnGId6Zlfbd1uBR6pl7NDgxW6+ePvR4g+yiHoYiOVbC/nD8A/eTsULpoAeOso49wltjVUps0c4Xd86tRc3hOZJlE1ClX6aJea2z6F7N3xgDnNsebEhZfZI1tIIyS5bL5WCt7ETF3PoCIz190pVp/l1tEX8ZtwqMbrbrrWzQQyxFkFtUkJmgqNnGWHmrU3PTCMQt3cynNrj1BR+/PX2MlMce/PVMOh4KkUYxR1ReDrPTazS9t/nzm1C3Qi3Q2FVLtfwsPDm9CO3uSScxngeXP2ZBvyrarIaEdWJowVQkBDjrTcY2fpZR8t41nNwEMNv0CEqs4n2DTSAl4l53bI9FLtE/gKEit8+blfK9arjjbUK19N5kcbjVoN0/CUQWs+8Hh7/lCYKFC46HFM5lwq6SeLmA6AOv9kzO+FURq27U7Df/prwXhhsL1BfAyrgIuMtMKQ6qYBxbW8nDSSFKC3C9TQWJePXfBLHGQmyM164HvKWzSWU4W21Sqk6t9gQ5EFFSBmOz+cpPNogZw1CvrAyDirf5Li8cHfNCigbnruhzYs5NLt7/2MCup5aJcl7VwK4pCLK4yyTpfzD+6Q98JRvUaQ="
