apiVersion: v1
kind: Pod
metadata:
  name: ingress-example
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: secrets-example
spec:
  containers:
    - name: secret-printer
      image: busybox
      args: [
        /bin/sh, -c,
        'while true; do echo "$(date) Secret: $(MY_SECRET_NAME). Message: $(MY_MESSAGE)"; sleep 2; done'
      ]
      env:
        - name: MY_SECRET_NAME
          valueFrom:
            secretKeyRef:
              name: my-secret-name
              key: my-secret-key
        - name: MY_MESSAGE
          value: {{ .Values.myMessage | default "no-value-specified"}}
